name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main  # ou o nome do seu ramo principal, ex: master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Passo para instalar dependências e fazer o build das Cloud Functions
      - name: Install Function Dependencies
        run: npm ci
        working-directory: ./functions # ✅ CORREÇÃO: Executa o comando dentro da pasta 'functions'

      # Passo para fazer o deploy no Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OLOMI_7816A }}'
          channelId: live
          projectId: olomi-7816a
