name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main # ou o nome do seu ramo principal, ex: master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ✅ CORREÇÃO DEFINITIVA: Trocado 'npm ci' por 'npm install'
      # O 'npm install' é mais flexível e não falhará se o package-lock.json estiver em falta.
      - name: Install Function Dependencies
        run: npm install
        working-directory: ./functions

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OLOMI_7816A }}'
          channelId: live
          projectId: olomi-7816a
